---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: crt
  labels:
    app: ${STARTUP}
    component: certificate
    namespace: ${STARTUP}-${NAMESPACE_ENVIRONMENT}
spec:
  secretName: crt
  commonName: ${ENVIRONMENT}.social.gouv.fr
  dnsNames:
    - ${APP_URL}
    - "*.egapro.${ENVIRONMENT}.social.gouv.fr"
  acme:
    config:
      - dns01:
          provider: azure/application-gateway
        domains:
          - ${APP_URL}
          - "*.egapro.${ENVIRONMENT}.social.gouv.fr"
  issuerRef:
    name: "letsencrypt-staging"
    kind: ClusterIssuer
