---

Install:
  extends: .base_yarn
  image: node:12.16.1-alpine3.11
  interruptible: true
  except:
    variables:
      - $PRODUCTION
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - yarn
      # NOTE(douglasduteil): do not upload node_modules
      # The full cache is too big for minio T_T
      # - node_modules
      # - packages/api/node_modules
      # - packages/app/node_modules
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
      - packages/api/node_modules
      - packages/app/node_modules

Lint:
  extends: .base_yarn_script
  image: node:12.16.1-alpine3.11
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn lint
  except:
    variables:
      - $PRODUCTION

Test api:
  extends: .base_yarn_script
  image: node:12.16.1-alpine3.11
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn workspace api test

Test app:
  extends: .base_yarn_script
  image: node:12.16.1-alpine3.11
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn workspace app test

Build app:
  extends: .base_yarn_script
  image: node:12.16.1-alpine3.11
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn workspace app build
  artifacts:
    expire_in: 1 day
    paths:
      - packages/app/build

Build api:
  extends: .base_yarn_script
  image: node:12.16.1-alpine3.11
  except:
    variables:
      - $PRODUCTION
  dependencies:
    - Install
  needs:
    - Install
  script:
    - yarn workspace api build
  artifacts:
    expire_in: 1 day
    paths:
      - packages/api/dist

...
