---

Backup before deploy to prod:
  stage: Registration
  image: ${CI_REGISTRY}/socialgouv/docker/kubectl:${KUBECTL_VERSION}
  script:
    - kubectl delete job 	backup-job -n ${K8S_NAMESPACE} || true;
    - kubectl apply -f .k8s/postgres/backup-job.yml -n ${K8S_NAMESPACE}
    - kubectl wait --for=condition=complete job/backup-job --timeout=600s -n ${K8S_NAMESPACE}
  environment:
    name: ${PROD_ENVIRONMENT_NAME}
  only:
    refs:
      - triggers
    variables:
      - $PRODUCTION

...
