on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

name: Install, build & test
jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check types
        run: |
          yarn type-check

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run test
        uses: yarn test

  build:
    runs-on: ubuntu-latest
    needs: [type-check, unit-test]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build