on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

name: Install, build and test egapro
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone reposotory
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Run the app
        run: yarn start